#define alarm___TCPAlarmTask0___absolutelifetime 0
#define alarm___TCPAlarmTask0___cycletime 0
#define applicationHeaders "appcode.h"
#define cfDEV_CGA_BASE_ADDRESS 0xb8000
#define cfDEV_E1000_DEVICE 0x100E
#define cfDEV_E1000_RXD_BUFFERSIZE 16
#define cfDEV_E1000_TXD_BUFFERSIZE 16
#define cfDEV_E1000_VENDOR 0x8086
#define cfDEV_PCI_CONFIGSPACE_MAXSIZE 32
#define cfDEV_PCI_CONFIG_ADDRESS 0x0CF8
#define cfDEV_PCI_CONFIG_DATA 0x0CFC
#define cfDEV_PIT_C0_ADDRESS 0x40
#define cfDEV_PIT_C1_ADDRESS 0x41
#define cfDEV_PIT_C2_ADDRESS 0x42
#define cfDEV_PIT_CTRL_ADDRESS 0x43
#define cfIPSTACK_BLOCKSIZE_BIG 1514
#define cfIPSTACK_BLOCKSIZE_SMALL 64
#define cfIPSTACK_COUNT_BIG 4
#define cfIPSTACK_COUNT_SMALL 4
#define cfIPSTACK_IPv6_cache 20
#define cfIPSTACK_MANAGEMENT_BLOCKSIZE_BIG 120
#define cfIPSTACK_MANAGEMENT_BLOCKSIZE_SMALL 64
#define cfIPSTACK_MANAGEMENT_COUNT_BIG 4
#define cfIPSTACK_MANAGEMENT_COUNT_SMALL 2
#define cfIPSTACK_MEMORY_MAX_RESET_SLOTS 2
#define cfOS_MAX_NUMBER_OF_EVENTS_PER_TASK 8
#define cfOS_MAX_PRIORITY 31
#define ciao_t32_pandaboard_user_script "pandaboard.cmm"
#define counter___SysCounter___maxallowedvalue 4294967295
#define counter___SysCounter___mincycle 1
#define counter___SysCounter___ticksperbase 1
#define task___Task0___activation 1
#define task___Task0___priority 2
#define task___Task0___stacksize 2048
