cmake_minimum_required (VERSION 2.8.8)
project (examples)

option (EXAMPLE_HTTP_SIMPLE_SERVER  "Html server" OFF) 
option (EXAMPLE_ICMP  "ICMPv4/v6 ping and udp ping" OFF) 
option (EXAMPLE_TCP_SPEEDTEST  "TCP Speedtest" OFF) 
option (EXAMPLE_TELNET  "Telnet" OFF) 

if (EXAMPLE_HTTP_SIMPLE_SERVER)
	SET(EXAMPLE_SRC "integration/http_simple_server/appcode.cpp" CACHE INTERNAL "")
endif()
if (EXAMPLE_ICMP)
	SET(EXAMPLE_SRC "integration/icmp_test/appcode.cpp" CACHE INTERNAL "")
endif()
if (EXAMPLE_TCP_SPEEDTEST)
	SET(EXAMPLE_SRC "integration/tcp_speedtest/appcode.cpp" CACHE INTERNAL "")
endif()
if (EXAMPLE_TELNET)
	SET(EXAMPLE_SRC "integration/telnet/appcode.cpp" CACHE INTERNAL "")
endif()